# Generated by Django 4.0.6 on 2022-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_issuetype_remove_issue_type_issue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issue5', through='webapp.IssueType', to='webapp.type'),
        ),
    ]
