# Generated by Django 4.0.6 on 2022-07-13 09:16

from django.db import migrations


def transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.types.set(issue.type.all())


def reverse_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type.set(issue.types.all())


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0003_issue_types_alter_issue_type'),
    ]

    operations = [
        migrations.RunPython(transfer, reverse_transfer)
    ]
