# Generated by Django 4.0.6 on 2022-07-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20220713_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.DeleteModel(
            name='IssueType',
        ),
    ]
