# Generated by Django 4.0.6 on 2022-07-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_issue_type_delete_issuetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец')),
                ('name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Полное описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
    ]
