# Generated by Django 4.0.6 on 2022-08-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('custom_permission', 'Менять участников проекта')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
